# This file was generated by GoReleaser. DO NOT EDIT.
class PubsubCli < Formula
  desc "Super handy cloud Pub/Sub CLI"
  homepage "https://github.com/k-yomo/pubsub_cli"
  version "1.2.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k-yomo/pubsub_cli/releases/download/v1.2.3/pubsub_cli_1.2.3_Darwin_x86_64.tar.gz"
    sha256 "210045fc1a197746e92d5f4a311f7f77d979589eb4fcaa62f359f45e64274792"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k-yomo/pubsub_cli/releases/download/v1.2.3/pubsub_cli_1.2.3_Linux_x86_64.tar.gz"
      sha256 "47c4a1374d0329eaacd68a2423922adcb75f91528f8cce840700a7411d83d793"
    end
  end

  def install
    bin.install "pubsub_cli"
  end

  test do
    system "#{bin}/pubsub_cli", "--version"
  end
end
