# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PubsubCli < Formula
  desc "Super handy cloud Pub/Sub CLI"
  homepage "https://github.com/k-yomo/pubsub_cli"
  version "1.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k-yomo/pubsub_cli/releases/download/v1.7.1/pubsub_cli_1.7.1_Darwin_x86_64.tar.gz"
      sha256 "c9b3a17bcba01d5b9136972e14555de74b4a3da5f6a91e2db7ba5f863f4a68b2"

      def install
        bin.install "pubsub_cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k-yomo/pubsub_cli/releases/download/v1.7.1/pubsub_cli_1.7.1_Darwin_arm64.tar.gz"
      sha256 "402ccd86aec1e874490c1cb92f01ac2fcdfd2064e2a3e6b7e36fb90d177c397d"

      def install
        bin.install "pubsub_cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k-yomo/pubsub_cli/releases/download/v1.7.1/pubsub_cli_1.7.1_Linux_x86_64.tar.gz"
      sha256 "ff78b0387df83e5d775a154e2a89e59ae90b7c04707c669c69b1e31b1b2f7ff2"

      def install
        bin.install "pubsub_cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k-yomo/pubsub_cli/releases/download/v1.7.1/pubsub_cli_1.7.1_Linux_arm64.tar.gz"
      sha256 "61e4649faee0c6231ef6c2b1438f57c5ba50ab971fe32931847e3cd9b71774bd"

      def install
        bin.install "pubsub_cli"
      end
    end
  end

  test do
    system "#{bin}/pubsub_cli", "--version"
  end
end
